--https://www.hackerrank.com/challenges/harry-potter-and-wands/problem

/*
WANDS -> ID, CODE, COINS_NEEDED, POWER
WANDS_PROPERTY -> CODE, AGE, IS_EVIL

OUTPUT: ID, AGE, COINS_NEEDED, POWER
*/
SELECT ID,
    AGE,
    COINS_NEEDED,
    POWER
FROM WANDS W
    JOIN WANDS_PROPERTY WP ON W.CODE = WP.CODE
WHERE IS_EVIL = 0
    AND COINS_NEEDED = (
        SELECT MIN(COINS_NEEDED)
        FROM WANDS WA
            JOIN WANDS_PROPERTY WAP ON WA.CODE = WAP.CODE
        WHERE WA.POWER = W.POWER
            AND WAP.AGE = WP.AGE
    )
ORDER BY POWER DESC,
    AGE DESC